### ISSUE TITLE
All Binary tree Problems

### ISSUE THREAD

**Issue by niteshkumar257** [ShankarYoda/CppAlgorithms#5]
DFS traversal
BFS traversal
Height of the Binary Tree
Diameter of the Binary Tree
Zig-zag traversal of the Binary Tree
Boundary Traversal of the Binary Tree
Right_view of the Binary Tree
Left_view of the Binary Tree
Minimum time to burn the Binary Tree
Max root to leaf path sum

**Comment by Veeno-Rai** [comment]
Please assign this issue to me. I  can handle it in cpp.
I had done All this in CP.

**Comment by Adityasaini10012001** [comment]
assign this to me

**Comment by Veeno-Rai** [comment]
All binary tree problem has been resolved kindly review it and approve !

**Comment by diglit123** [comment]
please assign it to me
